rmdir /s/q MyBlog.Business.Test\TestResults

mkdir TestResults
mkdir TestResults\reports

dotnet test --collect:"XPlat Code Coverage"

"%UserProfile%\.nuget\packages\reportgenerator\5.1.25\tools\net7.0\ReportGenerator.exe" -reports:MyBlog.*.Test\TestResults\*\coverage.cobertura.xml -reporttypes:Html;TeamCitySummary -targetdir:TestResults\reports -verbosity:Info -historydir:TestResults\reports\history -classfilters:-AutoGeneratedProgram;-MyBlog.Data.Migrations*;